workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: APP
    environment:
      unity: 2023.1.17f1
      xcode: 15.4
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.OfflinePlayingcards
      groups:
        - UNITY
      vars:
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "ios/Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.OfflinePlayingcards"
        APP_STORE_APPLE_ID: 6742623321
    scripts:
      - name: Clear Unity Cache
        script: |
          echo "Clearing Unity Library folder..."
          rm -rf Library/ && rm -rf Logs/

      - name: Install Unity Packages
        script: |
          echo "Forcing Unity to resolve packages..."
          $UNITY_HOME/Contents/MacOS/Unity -batchmode \
            -projectPath . \
            -executeMethod UnityEditor.PackageManager.Client.Resolve \
            -logFile \
            -quit

      - name: Activate Unity license
        script: | 
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile \
            -serial ${UNITY_SERIAL} \
            -username ${UNITY_EMAIL} \
            -password ${UNITY_PASSWORD}

      - name: Generate the Xcode project from Unity
        script: | 
          $UNITY_HOME/Contents/MacOS/Unity -batchmode \
            -quit \
            -logFile \
            -projectPath . \
            -executeMethod BuildScript.BuildIos \
            -nographics

      - name: Check if Xcode project exists
        script: |
          if [ -d "$UNITY_IOS_DIR/Unity-iPhone.xcodeproj" ]; then
            echo "Xcode project exists."
          else
            echo "ERROR: Xcode project not found!"
            exit 1
          fi

      - name: Show Unity Build Logs
        script: |
          cat ~/Library/Logs/Unity/Editor.log | tail -n 50

      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles

      - name: Set the build number
        script: | 
          BUILD_NUMBER=($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)
          cd $UNITY_IOS_DIR
          agvtool new-version -all $BUILD_NUMBER

      - name: Build the project
        script: | 
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      scripts:
        - name: Deactivate Unity License
          script: | 
            /Applications/Unity\ Hub.app/Contents/Frameworks/UnityLicensingClient_V1.app/Contents/MacOS/Unity.Licensing.Client \
            --return-ulf \
            --username ${UNITY_EMAIL} \
            --password ${UNITY_PASSWORD}

      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: true
