name: Build and Upload iOS to App Store

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    name: Build iOS and Upload to TestFlight
    runs-on: macos-latest
    steps:
      # ✅ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # ✅ Кэшируем библиотеку Unity
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-iOS
          restore-keys: Library-

      # ✅ Активируем лицензию Unity
      - name: Activate Unity License
        run: |
          echo "🔑 Activating Unity license..."
          UNITY_LICENSE_PATH=$HOME/.local/share/unity3d/Unity/Unity_lic.ulf
          echo "${{ secrets.UNITY_LICENSE }}" > "$UNITY_LICENSE_PATH"
          echo "✅ Unity license activated."

      # ✅ Запускаем билд Unity для iOS
      - name: Build iOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS

      # ✅ Проверяем, что IPA-файл создан
      - name: Check IPA file
        run: |
          if [ -f "build/iOS/*.ipa" ]; then
            echo "✅ IPA file found."
          else
            echo "❌ ERROR: IPA file not found!"
            exit 1
          fi

      # ✅ Загружаем IPA в App Store Connect
      - name: Upload iOS build to App Store
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/iOS/*.ipa
          app-store-connect-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          app-store-connect-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          app-store-connect-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          app-store-connect-app-id: "6742623321"

      # ✅ Очищаем лицензию после билда
      - name: Cleanup Unity License
        if: always()
        run: |
          echo "🗑️ Removing Unity license..."
          rm -f ~/.local/share/unity3d/Unity/Unity_lic.ulf
          echo "✅ Unity license removed."
