name: Build and Upload iOS to App Store

on: [push, pull_request]

jobs:
  build-ios:
    name: Build iOS Project
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-iOS
          restore-keys: Library-

      - name: Build Xcode Project from Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          buildMethod: IOSBuild.BuildIos  # Убедись, что Unity найдет этот класс
          buildName: Unity-iPhone
          buildPath: build/iOS

      - name: Verify Xcode Project
        run: |
          if [ ! -d "build/iOS/Unity-iPhone.xcodeproj" ]; then
            echo "❌ ERROR: Xcode project not found!"
            exit 1
          fi
          echo "✅ Xcode project found."

      - name: Archive Xcode Project
        run: |
          cd build/iOS
          xcodebuild -project Unity-iPhone.xcodeproj \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath output/Unity.xcarchive \
                     archive

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/iOS/output/Unity.xcarchive \
                     -exportPath build/iOS/output \
                     -exportOptionsPlist exportOptions.plist

      - name: Upload Artifact (iOS IPA)
        uses: actions/upload-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS/output/Unity.ipa

  upload-ios:
    name: Upload iOS Build to App Store
    runs-on: macos-latest
    needs: build-ios
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download iOS Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-iOS
          path: build/iOS/output

      - name: Verify .ipa File
        run: |
          if [ ! -f "build/iOS/output/Unity.ipa" ]; then
            echo "❌ ERROR: .ipa file not found!"
            exit 1
          fi
          echo "✅ .ipa file found."

      - name: Upload to App Store
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          echo "${APP_STORE_CONNECT_PRIVATE_KEY}" > AuthKey.p8
          xcrun altool --upload-app -f "build/iOS/output/Unity.ipa" -t ios --apiKey ${APP_STORE_CONNECT_KEY_ID} --apiIssuer ${APP_STORE_CONNECT_ISSUER_ID}
