name: Build and Upload iOS to App Store

on: [push, pull_request]

jobs:
  build-ios:
    name: Build iOS in Unity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-iOS
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          buildMethod: IOSBuild.BuildIos
      - uses: actions/upload-artifact@v4
        with:
          name: Unity-iOS-XcodeProject
          path: build/iOS

  export-ipa:
    name: Export .ipa from Xcode
    runs-on: macos-latest
    needs: build-ios
    steps:
      - uses: actions/checkout@v4
      - name: Download Unity Build
        uses: actions/download-artifact@v4
        with:
          name: Unity-iOS-XcodeProject
          path: build/iOS

      - name: Install Dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          brew install fastlane

      - name: Build and Export .ipa
        env:
          EXPORT_OPTIONS_PLIST: "exportOptions.plist"
        run: |
          cd build/iOS
          xcodebuild -workspace Unity-iPhone.xcworkspace \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/Unity.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath build/Unity.xcarchive \
                     -exportPath build \
                     -exportOptionsPlist $EXPORT_OPTIONS_PLIST

      - uses: actions/upload-artifact@v4
        with:
          name: iOS-ipa
          path: build/iOS/*.ipa

  upload-to-app-store:
    name: Upload iOS Build to App Store
    runs-on: macos-latest
    needs: export-ipa
    steps:
      - uses: actions/checkout@v4
      - name: Download .ipa Build
        uses: actions/download-artifact@v4
        with:
          name: iOS-ipa
          path: build/iOS

      - name: Upload to App Store
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        run: |
          echo "${APP_STORE_CONNECT_PRIVATE_KEY}" > AuthKey.p8
          xcrun altool --upload-app -f "build/iOS/*.ipa" -t ios \
                       --apiKey ${APP_STORE_CONNECT_KEY_ID} \
                       --apiIssuer ${APP_STORE_CONNECT_ISSUER_ID}
