name: Upload iOS App to App Store

on:
  workflow_dispatch:  # Запуск вручную
  push:
    tags:
      - "v*"  # Автоматический запуск при пуше нового тега (например, v1.0.0)

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Убедись, что версия поддерживается Fastlane
          bundler-cache: true  # Кеширует зависимости

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Create API Key File
        run: |
          echo "${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}" > AuthKey.p8
          chmod 600 AuthKey.p8  # Устанавливаем права доступа

      - name: Upload IPA to TestFlight
        run: |
          bundle exec fastlane pilot upload \
            --api_key_path AuthKey.p8 \
            --api_key_id "${{ secrets.APPSTORE_CONNECT_KEY_ID }}" \
            --issuer_id "${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}" \
            --ipa "your_app.ipa"

      - name: Cleanup
        run: rm -f AuthKey.p8  # Удаляем ключ безопасности после загрузки
